name: Release to staging/production

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release the application
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
